name: Trigger GitHub Pages rebuild at remote repos

on:
  workflow_dispatch:

jobs:
  GitHub-Pages-Rebuild:
    runs-on: ubuntu-latest

    steps:
    - name: rebuild vng-realisatie/Regels-bij-activiteiten
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $USER_TOKEN" \
        https://api.github.com/repos/vng-realisatie/Regels-bij-activiteiten/pages/builds
      env:
        USER_TOKEN: ${{ secrets.VNG_R_TOKEN }}

    - name: rebuild vng-realisatie/IMWOZ-bevragingen
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $USER_TOKEN" \
        https://api.github.com/repos/vng-realisatie/IMWOZ-bevragingen/pages/builds
      env:
        USER_TOKEN: ${{ secrets.VNG_R_TOKEN }}

    - name: rebuild vng-realisatie/IAM
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $USER_TOKEN" \
        https://api.github.com/repos/vng-realisatie/IAM/pages/builds
      env:
        USER_TOKEN: ${{ secrets.VNG_R_TOKEN }}

    - name: rebuild vng-realisatie/ODS-Open-Raadsinformatie
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $USER_TOKEN" \
        https://api.github.com/repos/vng-realisatie/ODS-Open-Raadsinformatie/pages/builds
      env:
        USER_TOKEN: ${{ secrets.VNG_R_TOKEN }}

    - name: rebuild vng-realisatie/API-Kennisbank
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $USER_TOKEN" \
        https://api.github.com/repos/vng-realisatie/API-Kennisbank/pages/builds
      env:
        USER_TOKEN: ${{ secrets.VNG_R_TOKEN }}

    - name: rebuild vng-realisatie/gemma-verwerkingenlogging
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $USER_TOKEN" \
        https://api.github.com/repos/vng-realisatie/gemma-verwerkingenlogging/pages/builds
      env:
        USER_TOKEN: ${{ secrets.VNG_R_TOKEN }}
